services:
  - postgresql
language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
rvm:
  - 2.4.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
before_script:
  - bin/rails db:create
  - bin/rails db:migrate
script:
  - bundle exec rubocop
  - bin/rails spec
